O CRISP-DM (Cross-Industry Standard Process for Data Mining) é a metodologia mais utilizada para organizar projetos de ciência de dados e mineração de dados, focada em transformar dados em valor de negócio através de seis etapas cíclicas: compreensão do negócio, entendimento dos dados, preparação, modelagem, avaliação e implantação.
As 6 Etapas do CRISP-DM:

Compreensão do Negócio (Business Understanding): Definir objetivos, requisitos e critérios de sucesso do projeto sob a perspectiva de negócio.

Entendimento dos Dados (Data Understanding): Coletar, explorar e identificar a qualidade dos dados disponíveis.

Preparação dos Dados (Data Preparation): Limpar, transformar e selecionar os dados para modelagem (fase geralmente mais demorada).

Modelagem (Modeling): Aplicar técnicas de machine learning ou estatística para criar o modelo.

Avaliação (Evaluation): Verificar se o modelo atende aos objetivos de negócio definidos inicialmente.

Implantação (Deployment): Colocar o modelo em produção, monitorar e documentar os resultados.

In [ ]:
# Manipulação de Dados

import pandas as pd

In [ ]:
df_vendas = pd.read_csv('/content/drive/MyDrive/!Data Python 2603/base_vendas.csv')
display(df_vendas)

In [ ]:
# mostrar as 5 primeiras linhas (padrão)
# caso queira mais linhas, informar entre ()

df_vendas.head(15)

In [ ]:
# mostrar as 5 últimas linhas (padrão)
# caso queira mais linhas, informar entre ()

df_vendas.tail(15)

In [ ]:
# mostrar a estrutura do arquivo
# linhas e colunas

df_vendas.shape

In [ ]:
# mostrar as informações do DataFrame

df_vendas.info()

In [ ]:
# mostrar a descrição do arquivo

df_vendas.describe().round(2)

In [ ]:
# mostrando apenas campos 'object' (strings)

df_vendas.describe(include='object')

In [ ]:
# mostrando todos os campos

df_vendas.describe(include='all')

In [ ]:
# mostrar os nomes das colunas

df_vendas.columns

In [ ]:
#mostrar a quantidade de valores únicos por coluna

df_vendas.nunique()

In [ ]:
# mostrar os valores únicos de uma coluna

df_vendas.Categoria.unique()

In [ ]:
df_vendas['Nome Funcionario'].unique()

In [ ]:
df_vendas.nome_loja.unique()

In [ ]:
# verificar valores nulos ou 'missing values'

df_vendas.isna().sum()

In [ ]:
df_vendas.isnull().sum()

In [ ]:
# mostrar se existem valores duplicados (linhas)

df_vendas.duplicated().sum()

In [ ]:
# mostrar se existem valores duplicados (colunas)

df_vendas['Nome Funcionario'].duplicated().sum()

In [55]:
print(
    'Máximo: ', df_vendas['quantidade'].max(),
    '\nMínimo: ', df_vendas['quantidade'].min(),
    '\nMediana: ', df_vendas['quantidade'].median(),
    '\nMédia: ', df_vendas['quantidade'].mean(),
    '\nModa: ',df_vendas['quantidade'].mode()
)

Máximo:  4
Mínimo:  1
Mediana:  2.0
Média:  2.453333333333333
Moda:  0    1
Name: quantidade, dtype: int64

## Exercício

## Fazer a análise exploratória de um Dataset obtido no site Airbnb

In [25]:
df_airbnb = pd.read_csv('/content/drive/MyDrive/!Data Python 2603/airbnb.csv')
display(df_airbnb)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,821198084644106078,Bright and Peaceful Leblon Loft,84350716,Katrina,NaN,Leblon,-22.982818,-43.222457,Entire home/apt,580.0,2,86,2025-09-19,2.72,1,82,40,NaN
1,821198370698658112,Copacabana 100% reformado.,4347269,Patrick,NaN,Copacabana,-22.984090,-43.191770,Entire home/apt,1900.0,5,0,NaN,NaN,2,364,0,NaN
2,821200521820144734,hambiente familia,499903412,Vanessa,NaN,Pavuna,-22.814911,-43.379011,Entire home/apt,700.0,1,0,NaN,NaN,2,365,0,NaN
3,821213014263313420,Amazing en suite bedroom Leblon,449763717,Alvaro,NaN,Leblon,-22.981910,-43.225990,Private room,NaN,2,3,2024-05-02,0.10,2,0,0,NaN
4,821223043903573522,Incrível apartamento frente mar,25961210,Katia,NaN,Barra da Tijuca,-23.010000,-43.344820,Entire home/apt,500.0,2,11,2025-08-26,0.60,1,234,10,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43063,1516476698580533369,Navegar É Preciso!,217513094,Carlos,NaN,Vidigal,-22.995090,-43.237380,Entire home/apt,85.0,5,0,NaN,NaN,2,148,0,NaN
43064,1516542813466248995,Apartamento lindo,551040994,Jario,NaN,Barra da Tijuca,-23.008243,-43.365345,Entire home/apt,860.0,1,0,NaN,NaN,1,365,0,NaN
43065,1516563369146268920,"Casa Maravilhosa, bem grande ótima localização.",91200104,David Nascentes Do Prado,NaN,Maracanã,-22.912503,-43.233881,Entire home/apt,129.0,3,0,NaN,NaN,3,251,0,NaN
43066,1516625258072383504,Copacabana Wave House (20% Off),452389314,Rafael,NaN,Leme,-22.962466,-43.167799,Entire home/apt,688.0,2,0,NaN,NaN,2,300,0,NaN
43067,1516641150127685299,Apt LULU 02 qts Melhor Localização!,3665789,Rosa Maria,NaN,Laranjeiras,-22.935427,-43.179370,Entire home/apt,340.0,5,0,NaN,NaN,8,120,0,NaN

In [26]:
df_airbnb.head(15)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,821198084644106078,Bright and Peaceful Leblon Loft,84350716,Katrina,NaN,Leblon,-22.982818,-43.222457,Entire home/apt,580.0,2,86,2025-09-19,2.72,1,82,40,NaN
1,821198370698658112,Copacabana 100% reformado.,4347269,Patrick,NaN,Copacabana,-22.984090,-43.191770,Entire home/apt,1900.0,5,0,NaN,NaN,2,364,0,NaN
2,821200521820144734,hambiente familia,499903412,Vanessa,NaN,Pavuna,-22.814911,-43.379011,Entire home/apt,700.0,1,0,NaN,NaN,2,365,0,NaN
3,821213014263313420,Amazing en suite bedroom Leblon,449763717,Alvaro,NaN,Leblon,-22.981910,-43.225990,Private room,NaN,2,3,2024-05-02,0.10,2,0,0,NaN
4,821223043903573522,Incrível apartamento frente mar,25961210,Katia,NaN,Barra da Tijuca,-23.010000,-43.344820,Entire home/apt,500.0,2,11,2025-08-26,0.60,1,234,10,NaN
5,821227099948297881,Apt N S de Copacabana reformado!,392769753,Amanda,NaN,Copacabana,-22.970696,-43.186048,Entire home/apt,461.0,2,89,2025-09-21,2.81,7,113,41,NaN
6,821240939360008287,Confortável apto no Leblon!,498395875,Martha,NaN,Leblon,-22.980368,-43.223114,Entire home/apt,NaN,3,68,2025-08-26,2.14,1,0,19,NaN
7,821242614763878451,Cozy space at Leme Beach,46944465,Ana Lucia,NaN,Leme,-22.963629,-43.172243,Entire home/apt,281.0,3,23,2025-05-05,0.73,1,32,8,NaN
8,821254575358803002,Quarto para duas pessoas,15991909,Yona,NaN,Copacabana,-22.976303,-43.194838,Private room,950.0,2,8,2025-05-04,0.26,3,89,1,NaN
9,821314145791532025,Quarto Master no Blue Hill,91654021,Daniel,NaN,Botafogo,-22.940620,-43.181620,Private room,450.0,3,0,NaN,NaN,151,90,0,NaN
10,821529031538759784,"Apto em Copa para 6 pessoas, a 1 minuto da praia!",8317871,Grace,NaN,Copacabana,-22.979539,-43.191163,Entire home/apt,1000.0,6,6,2024-09-15,0.19,4,7,0,NaN
11,821552389384274282,Cobertura linda e silenciosa,2911856,Joao,NaN,Copacabana,-22.974970,-43.194830,Entire home/apt,980.0,4,1,2025-01-01,0.11,1,164,1,NaN
12,821568077307009483,Suíte Duol Executiva -Barra Olímpica,492291708,Jacqueline,NaN,Camorim,-22.981152,-43.423539,Private room,177.0,1,13,2025-08-26,0.41,14,361,4,NaN
13,821590210039236935,M100 - Flat 3 minutes from Copacabana beach,51227019,Pedro,NaN,Copacabana,-22.973480,-43.185910,Entire home/apt,243.0,3,39,2025-09-01,1.22,24,40,15,NaN
14,821608275426250690,Wonderful Ocean View Loft,392083762,Laurent,NaN,Vidigal,-22.994578,-43.234801,Entire home/apt,346.0,2,39,2025-08-31,1.21,51,91,14,NaN

In [46]:
df_airbnb.tail(15)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
43053,1516238084442066280,4 Pax Copa Blue,334441936,Deisiane,NaN,Copacabana,-22.970249,-43.184160,Private room,527.0,1,0,NaN,NaN,9,327,0,NaN
43054,1516240724705898142,Aconchegante apart no Leme a 1 minuto da praia!,344580996,Rafael,NaN,Leme,-22.961740,-43.168830,Entire home/apt,350.0,2,0,NaN,NaN,1,333,0,NaN
43055,1516243781433483330,"Belíssimo quarto sala, a uma quadra da praia.",588586166,Vinicius,NaN,Copacabana,-22.980553,-43.190946,Entire home/apt,260.0,1,0,NaN,NaN,1,340,0,NaN
43056,1516244054123254161,loft praia flamengo,655641499,Wagner Rodrigues De,NaN,Flamengo,-22.929785,-43.174874,Entire home/apt,163.0,1,0,NaN,NaN,2,362,0,NaN
43057,1516250803235331277,Apartamento de luxo no coração do Leblon,78253983,Jaqueline,NaN,Leblon,-22.984189,-43.226972,Entire home/apt,614.0,3,0,NaN,NaN,6,74,0,NaN
43058,1516271236473383476,Amplo Apê Vista Verde & Mar - São Conrado,376765302,Felipe,NaN,São Conrado,-22.994740,-43.253440,Entire home/apt,510.0,2,0,NaN,NaN,14,364,0,NaN
43059,1516287670104699097,"Suíte Vista Mar com Banheira, Hotel, RJ-Brasil",221695083,Oscar,NaN,São Conrado,-22.997810,-43.255950,Private room,904.0,7,0,NaN,NaN,1,8,0,NaN
43060,1516306399226743180,Ocean Soul Pontal,345226004,Enzo,NaN,Recreio dos Bandeirantes,-23.028988,-43.473743,Entire home/apt,155.0,1,0,NaN,NaN,15,365,0,NaN
43061,1516335437848728496,Hotel Nacional na praia de São Conrado RJ,557975463,Alessandra,NaN,Vidigal,-22.996860,-43.237961,Private room,500.0,1,0,NaN,NaN,2,14,0,NaN
43062,1516421123954674179,Small but cozy apartment one block from the beach,492478277,Gabriela,NaN,Copacabana,-22.968520,-43.181370,Entire home/apt,175.0,7,0,NaN,NaN,1,147,0,NaN
43063,1516476698580533369,Navegar É Preciso!,217513094,Carlos,NaN,Vidigal,-22.995090,-43.237380,Entire home/apt,85.0,5,0,NaN,NaN,2,148,0,NaN
43064,1516542813466248995,Apartamento lindo,551040994,Jario,NaN,Barra da Tijuca,-23.008243,-43.365345,Entire home/apt,860.0,1,0,NaN,NaN,1,365,0,NaN
43065,1516563369146268920,"Casa Maravilhosa, bem grande ótima localização.",91200104,David Nascentes Do Prado,NaN,Maracanã,-22.912503,-43.233881,Entire home/apt,129.0,3,0,NaN,NaN,3,251,0,NaN
43066,1516625258072383504,Copacabana Wave House (20% Off),452389314,Rafael,NaN,Leme,-22.962466,-43.167799,Entire home/apt,688.0,2,0,NaN,NaN,2,300,0,NaN
43067,1516641150127685299,Apt LULU 02 qts Melhor Localização!,3665789,Rosa Maria,NaN,Laranjeiras,-22.935427,-43.179370,Entire home/apt,340.0,5,0,NaN,NaN,8,120,0,NaN

In [30]:
df_airbnb.shape

(43068, 18)

In [32]:
df_airbnb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43068 entries, 0 to 43067
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              43068 non-null  int64
 1   name                            43068 non-null  object
 2   host_id                         43068 non-null  int64
 3   host_name                       43057 non-null  object
 4   neighbourhood_group             0 non-null      float64
 5   neighbourhood                   43068 non-null  object
 6   latitude                        43068 non-null  float64
 7   longitude                       43068 non-null  float64
 8   room_type                       43068 non-null  object
 9   price                           38670 non-null  float64
 10  minimum_nights                  43068 non-null  int64
 11  number_of_reviews               43068 non-null  int64
 12  last_review                     33882 non-null  object
 13  reviews_per_month               33882 non-null  float64
 14  calculated_host_listings_count  43068 non-null  int64
 15  availability_365                43068 non-null  int64
 16  number_of_reviews_ltm           43068 non-null  int64
 17  license                         0 non-null      float64
dtypes: float64(6), int64(7), object(5)
memory usage: 5.9+ MB

In [33]:
df_airbnb.describe().round(2)

,id,host_id,neighbourhood_group,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
count,4.306800e+04,4.306800e+04,0.0,43068.00,43068.00,38670.00,43068.00,43068.00,33882.00,43068.00,43068.00,43068.00,0.0
mean,8.191760e+17,2.371628e+08,NaN,-22.97,-43.25,717.54,3.65,26.18,1.20,9.97,191.44,8.99,NaN
std,5.657082e+17,2.193633e+08,NaN,0.04,0.10,4388.08,15.39,48.65,1.31,26.12,126.14,13.35,NaN
min,1.787800e+04,3.607000e+03,NaN,-23.07,-43.71,30.00,1.00,0.00,0.01,1.00,0.00,0.00,NaN
25%,4.985161e+07,3.762061e+07,NaN,-22.98,-43.30,202.00,1.00,1.00,0.24,1.00,85.00,0.00,NaN
50%,1.029236e+18,1.596793e+08,NaN,-22.97,-43.19,317.00,2.00,7.00,0.74,2.00,177.00,3.00,NaN
75%,1.315246e+18,4.324447e+08,NaN,-22.95,-43.18,565.00,3.00,30.00,1.78,6.00,327.00,13.00,NaN
max,1.518231e+18,7.208012e+08,NaN,-22.75,-43.10,500000.00,1000.00,760.00,15.00,232.00,365.00,163.00,NaN

In [34]:
df_airbnb.describe(include='object')

,name,host_name,neighbourhood,room_type,last_review
count,43068,43057,43068,43068,33882
unique,40833,7725,152,4,1451
top,Apartamento em Copacabana,Daniel,Copacabana,Entire home/apt,2025-05-04
freq,171,455,13277,34495,1503

In [36]:
df_airbnb.describe(include='all').round(2)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
count,4.306800e+04,43068,4.306800e+04,43057,0.0,43068,43068.00,43068.00,43068,38670.00,43068.00,43068.00,33882,33882.00,43068.00,43068.00,43068.00,0.0
unique,NaN,40833,NaN,7725,NaN,152,NaN,NaN,4,NaN,NaN,NaN,1451,NaN,NaN,NaN,NaN,NaN
top,NaN,Apartamento em Copacabana,NaN,Daniel,NaN,Copacabana,NaN,NaN,Entire home/apt,NaN,NaN,NaN,2025-05-04,NaN,NaN,NaN,NaN,NaN
freq,NaN,171,NaN,455,NaN,13277,NaN,NaN,34495,NaN,NaN,NaN,1503,NaN,NaN,NaN,NaN,NaN
mean,8.191760e+17,NaN,2.371628e+08,NaN,NaN,NaN,-22.97,-43.25,NaN,717.54,3.65,26.18,NaN,1.20,9.97,191.44,8.99,NaN
std,5.657082e+17,NaN,2.193633e+08,NaN,NaN,NaN,0.04,0.10,NaN,4388.08,15.39,48.65,NaN,1.31,26.12,126.14,13.35,NaN
min,1.787800e+04,NaN,3.607000e+03,NaN,NaN,NaN,-23.07,-43.71,NaN,30.00,1.00,0.00,NaN,0.01,1.00,0.00,0.00,NaN
25%,4.985161e+07,NaN,3.762061e+07,NaN,NaN,NaN,-22.98,-43.30,NaN,202.00,1.00,1.00,NaN,0.24,1.00,85.00,0.00,NaN
50%,1.029236e+18,NaN,1.596793e+08,NaN,NaN,NaN,-22.97,-43.19,NaN,317.00,2.00,7.00,NaN,0.74,2.00,177.00,3.00,NaN
75%,1.315246e+18,NaN,4.324447e+08,NaN,NaN,NaN,-22.95,-43.18,NaN,565.00,3.00,30.00,NaN,1.78,6.00,327.00,13.00,NaN
max,1.518231e+18,NaN,7.208012e+08,NaN,NaN,NaN,-22.75,-43.10,NaN,500000.00,1000.00,760.00,NaN,15.00,232.00,365.00,163.00,NaN

In [49]:
df_airbnb.columns

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'number_of_reviews_ltm', 'license'],
      dtype='object')

In [38]:
df_airbnb.nunique()

id                                43068
name                              40833
host_id                           24993
host_name                          7725
neighbourhood_group                   0
neighbourhood                       152
latitude                          26137
longitude                         27483
room_type                             4
price                              2600
minimum_nights                       70
number_of_reviews                   426
last_review                        1451
reviews_per_month                   772
calculated_host_listings_count       65
availability_365                    366
number_of_reviews_ltm               119
license                               0
dtype: int64

In [47]:
df_airbnb.neighbourhood.unique()

array(['Leblon', 'Copacabana', 'Pavuna', 'Barra da Tijuca', 'Leme',
       'Botafogo', 'Camorim', 'Vidigal', 'Santíssimo', 'Humaitá',
       'Centro', 'Jacarepaguá', 'Santa Teresa',
       'Recreio dos Bandeirantes', 'Flamengo', 'Jardim Botânico',
       'Tijuca', 'Engenheiro Leal', 'Estácio', 'São Conrado', 'Itanhangá',
       'Catete', 'Ipanema', 'Marechal Hermes', 'Cidade Nova', 'Grajaú',
       'Santa Cruz', 'Campo Grande', 'Freguesia (Jacarepaguá)',
       'Rio Comprido', 'Barra de Guaratiba', 'Laranjeiras',
       'Vigário Geral', 'Engenho de Dentro', 'Urca', 'Vargem Pequena',
       'Lagoa', 'Irajá', 'Vila Isabel', 'Gávea', 'Cacuia', 'Anil',
       'Cosme Velho', 'Del Castilho', 'Vargem Grande', 'São Cristóvão',
       'Jardim Sulacap', 'Bonsucesso', 'Bento Ribeiro', 'Méier',
       'Catumbi', 'Maracanã', 'Santo Cristo', 'São Francisco Xavier',
       'Paquetá', 'Joá', 'Penha Circular', 'Taquara', 'Rocha Miranda',
       'Vaz Lobo', 'Praça da Bandeira', 'Brás de Pina', 'Inhaúma',
       'Curicica', 'Praça Seca', 'Vila da Penha', 'Glória',
       'Alto da Boa Vista', 'Rocinha', 'Bangu', 'Lins de Vasconcelos',
       'Gamboa', 'Engenho Novo', 'Piedade', 'Guaratiba', 'Portuguesa',
       'Cavalcanti', 'Cachambi', 'Riachuelo', 'Higienópolis',
       'Gardênia Azul', 'Todos os Santos', 'Pilares', 'Andaraí', 'Penha',
       'Quintino Bocaiúva', 'Tauá', 'Pechincha', 'Inhoaíba', 'Gericinó',
       'Sampaio', 'Rocha', 'Ricardo de Albuquerque', 'Jardim Guanabara',
       'Campinho', 'Abolição', 'Realengo', 'Vila Valqueire', 'Anchieta',
       'Moneró', 'Encantado', 'Guadalupe', 'Ramos', 'Cidade de Deus',
       'Parque Anchieta', 'Pedra de Guaratiba', 'Osvaldo Cruz',
       'Vasco da Gama', 'Tanque', 'Água Santa', 'Cocotá',
       'Praia da Bandeira', 'Sepetiba', 'Zumbi', 'Vicente de Carvalho',
       'Engenho da Rainha', 'Parada de Lucas', 'Cascadura',
       'Jardim Carioca', 'Senador Vasconcelos', 'Grumari', 'Cordovil',
       'Paciência', 'Coelho Neto', 'Vila Kosmos', 'Honório Gurgel',
       'Cosmos', 'Benfica', 'Senador Camará', 'Vila Militar', 'Bancários',
       'Pitangueiras', 'Saúde', 'Jacaré', 'Olaria', 'Maria da Graça',
       'Madureira', 'Padre Miguel', 'Turiaçú', 'Barros Filho',
       'Freguesia (Ilha)', 'Ribeira', 'Tomás Coelho', 'Maré', 'Colégio',
       'Mangueira', 'Complexo do Alemão', 'Galeão', 'Manguinhos',
       'Cidade Universitária', 'Magalhães Bastos', 'Caju'], dtype=object)

In [50]:
df_airbnb.isnull().sum()

id                                    0
name                                  0
host_id                               0
host_name                            11
neighbourhood_group               43068
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                              4398
minimum_nights                        0
number_of_reviews                     0
last_review                        9186
reviews_per_month                  9186
calculated_host_listings_count        0
availability_365                      0
number_of_reviews_ltm                 0
license                           43068
dtype: int64

In [51]:
df_airbnb.duplicated().sum()

np.int64(0)

In [52]:
df_airbnb.neighbourhood.duplicated().sum()

np.int64(42916)